# Generated by Django 4.1 on 2022-08-06 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cleaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('Th', 'Thursday'), ('F', 'Friday'), ('S', 'Saturday'), ('Sun', 'Sunday')], default='M', max_length=8)),
                ('month', models.CharField(max_length=8)),
                ('rock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.rock')),
            ],
        ),
    ]
