# Generated by Django 4.1 on 2022-08-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_painting_alter_cleaning_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='rock',
            name='painting',
            field=models.ManyToManyField(to='main_app.painting'),
        ),
    ]
